### PR TITLE
useNativeDriver

### PR DESCRIPTION
**Pull request by slorber**

### CODE REVIEW

**Comment by prscX** [comment]
Hi @n4kz: Any update on merging the PR? Post your review, can you please merge this PR.

Thanks
</ Pranav >

**Comment by n4kz** [comment]
Thanks for PR and sorry for delayed reply.

**Comment by slorber** [comment]
😅 Thanks, totally forgot it

**Comment by n4kz** [comment]
Sadly had to revert this. For now many animations in RN are not working with native driver enabled, even `backgroundColor`. Since I've used `backgroundColor` in animated transition to disabled state I see no easy way to make this optional :(

**Pull request merged**
